### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Bixilon** [walt-grace/glsl-plugin-idea#1]
Hey,

thanks for the extension!

Can you please publish the code? Really interested and even improving one feature ;)

Thanks

Moritz

**Comment by walt-grace** [comment]
Hi Moritz 
I'll try to do that this. Been planning that for a long time already.

**Comment by Bixilon** [comment]
Whats the difficulty?

Am 19. September 2022 11:18:07 MESZ schrieb Roi Mordechay ***@***.***>:

**Comment by coffeenotfound** [comment]
Open sourcing would be great. Im sure some people would love to chip in with contributions!

**Comment by walt-grace** [comment]
Sorry guys. I had zero time in the past weeks to get back the project. 
@Bixilon Reason is the that I want to start a complete new git repository since there is so much rubbish there from initial development, and more importantly, the secret token is also there in very early commits. The problem is that I'm in a middle of work and that will just caused me unnecessary work if I take care on both at the same time. So basically I want to release a new version, start a new blank git tree, and post the the code with a complete clean state. 

If you are just interested in seeing the code for now, let me know. I can email you the code.

**Comment by walt-grace** [comment]
@coffeenotfound  @Bixilon  Code is uploaded.

**Comment by Bixilon** [comment]
Thank you!
